# -*- coding: utf-8 -*-
"""
Training script optimized for Kaggle environment
Modified from original train.py to work with RAF-DB dataset on Kaggle
"""
import datetime
import os
from functools import partial

import numpy as np
import torch
import torch.backends.cudnn as cudnn
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from nets.yolo import YoloBody
from nets.yolo_training import (ModelEMA, YOLOLoss, get_lr_scheduler,
                                set_optimizer_lr, weights_init)
from utils.callbacks import EvalCallback, LossHistory
from utils.dataloader import YoloDataset, yolo_dataset_collate
from utils.utils import (get_classes, seed_everything, show_config,
                         worker_init_fn)
from utils.utils_fit import fit_one_epoch

if __name__ == "__main__":
    # ============================================
    # CONFIGURATION
    # ============================================
    # Image paths are embedded in raf_train.txt / raf_val.txt
    # (generated by convert_raf_to_yolo.py).
    # No path configuration needed here.
    is_kaggle = os.path.exists('/kaggle')
    Cuda      = torch.cuda.is_available()
    print(f"Environment : {'Kaggle' if is_kaggle else 'Local'}")
    print(f"CUDA        : {Cuda}")
    
    # ============================================
    # TRAINING PARAMETERS  (auto-tuned to the GPU, overridable via env vars)
    # ============================================
    # Nothing here needs editing to switch machines. Any value can be overridden
    # from the command line, e.g. to fit a smaller GPU or do a quick smoke test:
    #     UNFREEZE_BATCH=4 FREEZE_BATCH=8 EPOCHS=2 python train_kaggle.py
    def _env(name, default, cast):
        v = os.environ.get(name)
        if v is None or v == "":
            return default
        try:
            return cast(v)
        except (ValueError, TypeError):
            print(f"  [config] ignoring invalid {name}={v!r}, using default {default}")
            return default

    def _env_bool(name, default):
        v = os.environ.get(name)
        if v is None or v == "":
            return default
        return v.strip().lower() in ("1", "true", "yes", "y", "on")

    # ---- Pick a default profile from the detected VRAM ----
    if Cuda:
        _vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
        _gpu_name = torch.cuda.get_device_name(0)
    else:
        _vram_gb, _gpu_name = 0.0, "CPU"

    if _vram_gb >= 40:        # A100 40GB / RTX 6000 Ada 48GB
        _p = dict(inp=224, fbs=32, ubs=32, workers=8)
    elif _vram_gb >= 22:      # 24GB: RTX 3090/4090, L4, A10
        _p = dict(inp=224, fbs=32, ubs=32, workers=6)
    elif _vram_gb >= 14:      # 16GB: Kaggle T4, V100
        _p = dict(inp=224, fbs=32, ubs=32, workers=4)
    elif _vram_gb >= 10:      # 12GB
        _p = dict(inp=224, fbs=16, ubs=16, workers=4)
    else:                     # smaller / unknown
        _p = dict(inp=224, fbs=8,  ubs=8,  workers=2)

    print(f"GPU         : {_gpu_name}  ({_vram_gb:.1f} GB)")

    seed            = _env("SEED", 11, int)
    distributed     = False
    sync_bn         = False
    fp16            = False                                        # AMP disabled
    classes_path    = os.environ.get("CLASSES_PATH", 'model_data/sfew_classes.txt')
    model_path      = os.environ.get("MODEL_PATH", 'model_data/yolox_s.pth')
    _inp            = _env("INPUT_SIZE", _p["inp"], int)
    input_shape     = [_inp, _inp]
    phi             = os.environ.get("PHI", 's')

    # Data augmentation
    mosaic              = True
    mosaic_prob         = 0.5
    mixup               = True
    mixup_prob          = 0.5
    special_aug_ratio   = 0.7

    # Training epochs / batch sizes
    Init_Epoch          = _env("INIT_EPOCH", 0, int)
    Freeze_Epoch        = _env("FREEZE_EPOCH", 50, int)
    Freeze_batch_size   = _env("FREEZE_BATCH", _p["fbs"], int)
    UnFreeze_Epoch      = _env("EPOCHS", 250, int)               # 250 epochs
    Unfreeze_batch_size = _env("UNFREEZE_BATCH", _p["ubs"], int)
    Freeze_Train        = _env_bool("FREEZE_TRAIN", True)
    patience            = _env("PATIENCE", 50, int)              # early stopping

    # Optimizer settings
    Init_lr             = _env("INIT_LR", 1e-2, float)
    Min_lr              = Init_lr * 0.01
    optimizer_type      = os.environ.get("OPTIMIZER", "sgd")
    momentum            = 0.937
    weight_decay        = 5e-4
    lr_decay_type       = "cos"

    # Checkpointing
    save_period         = _env("SAVE_PERIOD", 10, int)
    save_dir            = os.environ.get("SAVE_DIR", 'logs')
    eval_flag           = True
    eval_period         = _env("EVAL_PERIOD", 10, int)

    num_workers         = _env("NUM_WORKERS", _p["workers"], int)

    # Annotation paths - generated by convert_raf_to_yolo.py
    train_annotation_path   = os.environ.get("TRAIN_ANN", 'raf_train.txt')
    val_annotation_path     = os.environ.get("VAL_ANN", 'raf_val.txt')

    print(f"Config      : input {input_shape[0]}x{input_shape[0]}, "
          f"freeze_bs {Freeze_batch_size}, unfreeze_bs {Unfreeze_batch_size}, "
          f"workers {num_workers}, epochs {UnFreeze_Epoch}, fp16 {fp16}")
    if not Cuda:
        print("\nWARNING: no CUDA GPU detected. FER-YOLO-Mamba relies on custom CUDA "
              "kernels (selective_scan_cuda) and cannot train on CPU.\n"
              "         Use a GPU runtime (Kaggle GPU accelerator, or a RunPod CUDA template).")
    elif _vram_gb < 16:
        print("  [hint] On CUDA out-of-memory, lower the batch size, e.g.:")
        print("         UNFREEZE_BATCH=4 FREEZE_BATCH=8 python train_kaggle.py")
    
    # ============================================
    # SETUP
    # ============================================
    seed_everything(seed)

    ngpus_per_node  = torch.cuda.device_count()
    if distributed:
        dist.init_process_group(backend="nccl")
        local_rank  = int(os.environ["LOCAL_RANK"])
        rank        = int(os.environ["RANK"])
        device      = torch.device("cuda", local_rank)
        if local_rank == 0:
            print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) training...")
            print("Gpu Device Count : ", ngpus_per_node)
    else:
        device          = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        local_rank      = 0
        rank            = 0

    print(f"Using device: {device}")
    
    # ============================================
    # MODEL SETUP
    # ============================================
    class_names, num_classes = get_classes(classes_path)
    print(f"Classes: {class_names}")
    print(f"Number of classes: {num_classes}")

    model = YoloBody(num_classes, phi)
    weights_init(model)
    
    if model_path != '' and os.path.exists(model_path):
        if local_rank == 0:
            print('Load weights {}.'.format(model_path))
        model_dict      = model.state_dict()
        try:
            pretrained_dict = torch.load(model_path, map_location = device)
        except Exception:
            # torch>=2.6 defaults to weights_only=True; legacy checkpoints need this
            pretrained_dict = torch.load(model_path, map_location = device, weights_only=False)
        load_key, no_load_key, temp_dict = [], [], {}
        for k, v in pretrained_dict.items():
            if k in model_dict.keys() and np.shape(model_dict[k]) == np.shape(v):
                temp_dict[k] = v
                load_key.append(k)
            else:
                no_load_key.append(k)
        model_dict.update(temp_dict)
        model.load_state_dict(model_dict)

        if local_rank == 0:
            print("\nSuccessful Load Key:", str(load_key)[:500], "……\nSuccessful Load Key Num:", len(load_key))
            print("\nFail To Load Key:", str(no_load_key)[:500], "……\nFail To Load Key num:", len(no_load_key))
    else:
        if local_rank == 0:
            print(f"Warning: Model weights not found at {model_path}, training from scratch")

    yolo_loss    = YOLOLoss(num_classes, fp16)

    if local_rank == 0:
        time_str        = datetime.datetime.strftime(datetime.datetime.now(),'%Y_%m_%d_%H_%M_%S')
        log_dir         = os.path.join(save_dir, "loss_" + str(time_str))
        loss_history    = LossHistory(log_dir, model, input_shape=input_shape)
    else:
        loss_history    = None
        
    if fp16:
        try:
            scaler = torch.amp.GradScaler('cuda')
        except (AttributeError, TypeError):
            from torch.cuda.amp import GradScaler
            scaler = GradScaler()
    else:
        scaler = None

    model_train     = model.train()
    if sync_bn and ngpus_per_node > 1 and distributed:
        model_train = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model_train)
    elif sync_bn:
        print("Sync_bn is not support in one gpu or not distributed.")
    
    if Cuda:
        model_train = model_train.cuda()

    ema = ModelEMA(model_train)
    
    # ============================================
    # LOAD ANNOTATIONS
    # ============================================
    if not os.path.exists(train_annotation_path):
        raise FileNotFoundError(
            f"Training annotation file not found: {train_annotation_path}\n"
            f"Please run convert_raf_to_yolo.py first to generate annotation files!"
        )
    if not os.path.exists(val_annotation_path):
        raise FileNotFoundError(
            f"Validation annotation file not found: {val_annotation_path}\n"
            f"Please run convert_raf_to_yolo.py first to generate annotation files!"
        )
    
    with open(train_annotation_path, encoding='utf-8') as f:
        train_lines = f.readlines()
    with open(val_annotation_path, encoding='utf-8') as f:
        val_lines   = f.readlines()
    num_train   = len(train_lines)
    num_val     = len(val_lines)
     
    if local_rank == 0:
        show_config(
            classes_path = classes_path, model_path = model_path, input_shape = input_shape, \
            Init_Epoch = Init_Epoch, Freeze_Epoch = Freeze_Epoch, UnFreeze_Epoch = UnFreeze_Epoch, \
            Freeze_batch_size = Freeze_batch_size, Unfreeze_batch_size = Unfreeze_batch_size, Freeze_Train = Freeze_Train, \
            Init_lr = Init_lr, Min_lr = Min_lr, optimizer_type = optimizer_type, momentum = momentum, lr_decay_type = lr_decay_type, \
            save_period = save_period, save_dir = save_dir, num_workers = num_workers, num_train = num_train, num_val = num_val
        )
        wanted_step = 5e4 if optimizer_type == "sgd" else 1.5e4
        total_step  = num_train // Unfreeze_batch_size * UnFreeze_Epoch
        print(f"Total training steps: {total_step}")
        
    # ============================================
    # TRAINING LOOP
    # ============================================
    if True:
        UnFreeze_flag = False
        if Freeze_Train:
            for param in model.backbone.parameters():
                param.requires_grad = False
        batch_size = Freeze_batch_size if Freeze_Train else Unfreeze_batch_size

        nbs             = 64
        lr_limit_max    = 1e-3 if optimizer_type == 'adam' else 5e-2
        lr_limit_min    = 3e-4 if optimizer_type == 'adam' else 5e-4
        Init_lr_fit     = min(max(batch_size / nbs * Init_lr, lr_limit_min), lr_limit_max)
        Min_lr_fit      = min(max(batch_size / nbs * Min_lr, lr_limit_min * 1e-2), lr_limit_max * 1e-2)

        pg0, pg1, pg2 = [], [], []  
        for k, v in model.named_modules():
            if hasattr(v, "bias") and isinstance(v.bias, nn.Parameter):
                pg2.append(v.bias)    
            if isinstance(v, nn.BatchNorm2d) or "bn" in k:
                pg0.append(v.weight)    
            elif hasattr(v, "weight") and isinstance(v.weight, nn.Parameter):
                pg1.append(v.weight)   
        optimizer = {
            'adam'  : optim.Adam(pg0, Init_lr_fit, betas = (momentum, 0.999)),
            'sgd'   : optim.SGD(pg0, Init_lr_fit, momentum = momentum, nesterov=True)
        }[optimizer_type]
        optimizer.add_param_group({"params": pg1, "weight_decay": weight_decay})
        optimizer.add_param_group({"params": pg2})

        lr_scheduler_func = get_lr_scheduler(lr_decay_type, Init_lr_fit, Min_lr_fit, UnFreeze_Epoch)

        epoch_step      = num_train // batch_size
        epoch_step_val  = num_val // batch_size
        
        if ema:
            ema.updates     = epoch_step * Init_Epoch
            
        train_dataset   = YoloDataset(train_lines, input_shape, num_classes, epoch_length = UnFreeze_Epoch, \
                                            mosaic=mosaic, mixup=mixup, mosaic_prob=mosaic_prob, mixup_prob=mixup_prob, train=True, special_aug_ratio=special_aug_ratio)
        val_dataset     = YoloDataset(val_lines, input_shape, num_classes, epoch_length = UnFreeze_Epoch, \
                                            mosaic=False, mixup=False, mosaic_prob=0, mixup_prob=0, train=False, special_aug_ratio=0)
        
        if distributed:
            train_sampler   = torch.utils.data.distributed.DistributedSampler(train_dataset, shuffle=True,)
            val_sampler     = torch.utils.data.distributed.DistributedSampler(val_dataset, shuffle=False,)
            batch_size      = batch_size // ngpus_per_node
            shuffle         = False
        else:
            train_sampler   = None
            val_sampler     = None
            shuffle         = True

        gen             = DataLoader(train_dataset, shuffle = shuffle, batch_size = batch_size, num_workers = num_workers, pin_memory=True,
                                    drop_last=True, collate_fn=yolo_dataset_collate, sampler=train_sampler, 
                                    worker_init_fn=partial(worker_init_fn, rank=rank, seed=seed))
        gen_val         = DataLoader(val_dataset  , shuffle = shuffle, batch_size = batch_size, num_workers = num_workers, pin_memory=True, 
                                    drop_last=True, collate_fn=yolo_dataset_collate, sampler=val_sampler, 
                                    worker_init_fn=partial(worker_init_fn, rank=rank, seed=seed))
        
        if local_rank == 0:
            eval_callback   = EvalCallback(model, input_shape, class_names, num_classes, val_lines, log_dir, Cuda, \
                                            eval_flag=eval_flag, period=eval_period)
        else:
            eval_callback   = None

        # Early stopping state
        _best_loss      = float('inf')
        _no_improve     = 0

        for epoch in range(Init_Epoch, UnFreeze_Epoch):
            if epoch >= Freeze_Epoch and not UnFreeze_flag and Freeze_Train:
                batch_size = Unfreeze_batch_size
                nbs             = 64
                lr_limit_max    = 1e-3 if optimizer_type == 'adam' else 5e-2
                lr_limit_min    = 3e-4 if optimizer_type == 'adam' else 5e-4
                Init_lr_fit     = min(max(batch_size / nbs * Init_lr, lr_limit_min), lr_limit_max)
                Min_lr_fit      = min(max(batch_size / nbs * Min_lr, lr_limit_min * 1e-2), lr_limit_max * 1e-2)
                lr_scheduler_func = get_lr_scheduler(lr_decay_type, Init_lr_fit, Min_lr_fit, UnFreeze_Epoch)
                
                for param in model.backbone.parameters():
                    param.requires_grad = True

                epoch_step      = num_train // batch_size
                epoch_step_val  = num_val // batch_size

                if distributed:
                    batch_size = batch_size // ngpus_per_node
                    
                if ema:
                    ema.updates     = epoch_step * epoch
                    
                gen             = DataLoader(train_dataset, shuffle = shuffle, batch_size = batch_size, num_workers = num_workers, pin_memory=True,
                                            drop_last=True, collate_fn=yolo_dataset_collate, sampler=train_sampler, 
                                            worker_init_fn=partial(worker_init_fn, rank=rank, seed=seed))
                gen_val         = DataLoader(val_dataset  , shuffle = shuffle, batch_size = batch_size, num_workers = num_workers, pin_memory=True, 
                                            drop_last=True, collate_fn=yolo_dataset_collate, sampler=val_sampler, 
                                            worker_init_fn=partial(worker_init_fn, rank=rank, seed=seed))
                UnFreeze_flag = True

            gen.dataset.epoch_now       = epoch
            gen_val.dataset.epoch_now   = epoch

            if distributed:
                train_sampler.set_epoch(epoch)

            set_optimizer_lr(optimizer, lr_scheduler_func, epoch)

            fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)

            # ── Early stopping ──────────────────────────────────────────
            if local_rank == 0 and loss_history is not None and len(loss_history.val_loss) > 0:
                current_val_loss = loss_history.val_loss[-1]
                if current_val_loss < _best_loss:
                    _best_loss  = current_val_loss
                    _no_improve = 0
                    print(f"  [EarlyStopping] val_loss improved to {_best_loss:.4f}")
                else:
                    _no_improve += 1
                    print(f"  [EarlyStopping] no improvement for {_no_improve}/{patience} epochs")
                    if _no_improve >= patience:
                        print(f"\n  [EarlyStopping] Stopping at epoch {epoch+1} — "
                              f"val_loss did not improve for {patience} consecutive epochs.")
                        break

            if distributed:
                dist.barrier()

        if local_rank == 0:
            loss_history.writer.close()
            print("\n" + "="*50)
            print("Training completed!")
            print(f"Model checkpoints saved in: {save_dir}")
            print("="*50)
